### ISSUE TITLE
Audit Failure in `getAuditConfig`

### ISSUE THREAD

**Issue by solaris007** [adobe/spacecat-audit-worker#208]
Some audits fail with:
```json
{
  "timestamp": "2024-04-08T02:23:44.264Z",
  "logStream": "2024/04/08/[943]2899d868675547779eae7e47bcab50a4",
  "message": "Audit failed after 0.04 seconds Error: apex audit failed for site cfa8874a-2e4b-4aa3-97ea-c52fc1d7f7df. Reason: Cannot read properties of null (reading 'getAuditConfig')
    at Audit.run (/var/task/index.js:34021:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async run (/var/task/index.js:34365:20)
    at async lambdaAdapter (/var/task/index.js:4463:24)
    at async Runtime.wrapped [as handler] (/var/task/index.js:4526:14)",
  "inv": {
    "invocationId": "e0df2dd6-b873-568d-ac87-735bef038b49",
    "functionName": "/spacecat-services/audit-worker/v1"
  },
  "level": "error"
}
```

**Comment by solaris007** [comment]
The issue was that the audit worker's configuration did not set which dynamo db table to use for organizations, so it defaulted to the dev-table on prod. This cause organizations to not be found for sites and the audit disabled check to fail.
